### ISSUE TITLE
fix(military): cross-Strait seeder crashes every tick — afterPublish meta object lands in the DI writer slot

### ISSUE THREAD

**Issue by koala73** [koala73/worldmonitor#5614]
`seed-cross-strait-activity` crashes **every tick** with `TypeError: writer is not a function`, so the cross-Strait seed never finishes publishing. Regression from #5575 / PR #5596. Reproduced deterministically (see below).

## Root cause

`runSeed` invokes the hook with a **metadata object** as the second positional arg (`scripts/_seed-utils.mjs:1998`):

```js
await afterPublish(data, { canonicalKey, ttlSeconds, recordCount, runId });
```

`scripts/seed-cross-strait-activity.mjs:155` wires `writePublicationCompletion` in directly:

```js
afterPublish: writePublicationCompletion,
```

but that function takes a **dependency-injected writer** in slot 2 (`scripts/seed-cross-strait-activity.mjs:94-98`):

```js
export async function writePublicationCompletion(snapshot, writer = writeExtraKey, completedAt = Date.now())
```

The `= writeExtraKey` default only applies when the arg is `undefined`. runSeed always passes the meta object, so `writer` is an object and the first call at `scripts/seed-cross-strait-activity.mjs:84` throws. Every other seeder wraps the hook in a lambda (`afterPublish: async (data) => {…}` in `seed-commodity-quotes.mjs:310`, `seed-cross-source-signals.mjs:890`, `seed-global-tenders.mjs:355`), which is why only this one breaks.

### Reproduction (exact production call shape)

```js
await writePublicationCompletion(snapshot, { canonicalKey: 'military:cross-strait-activity:v1', ttlSeconds: 1, recordCount: 1, runId: 'x' });
// -> TypeError: writer is not a function
```

Production log, deployment `c177edb3-f23e-4b74-aca5-54d16122c819` (`railway logs c177edb3-f23e-4b74-aca5-54d16122c819 -d`):

```
[Cross-Strait-Activity] file:///app/seed-cross-strait-activity.mjs:84
[Cross-Strait-Activity]     await writer(sourceHealthKey(source.id), source, CROSS_STRAIT_ACTIVITY_TTL_SECONDS);
[Cross-Strait-Activity] TypeError: writer is not a function
    at writeSourceHealth (file:///app/seed-cross-strait-activity.mjs:81:47)
    at writePublicationCompletion (file:///app/seed-cross-strait-activity.mjs:99:9)
    at runSeed (file:///app/_seed-utils.mjs:1989:13)
[Bundle:derived-signals] section=Cross-Strait-Activity status=FAILED elapsed=20.1s reason=exit 1
```

## Impact

The throw lands **after** the canonical + bootstrap writes but **before** `writeFreshnessMetadataSafely` (`scripts/_seed-utils.mjs:2018`), so everything downstream of the hook is permanently unwritten. Confirmed against `/api/health?compact=1`. `EMPTY` classifies as crit and `STALE_SEED` as warn (`api/health.js:1010,1022`), so this bug owns **2 of the 4 crit** plus 1 warn:

| health entry | key | state |
|---|---|---|
| `crossStraitActivity` | `seed-meta:military:cross-strait-activity` | `STALE_SEED`, `seedAgeMin` undefined — never written |
| `crossStraitActivityTaiwanMnd` | `military:cross-strait-activity:v1:source:taiwan-mnd` | `EMPTY` |
| `crossStraitActivityJapanMod` | `military:cross-strait-activity:v1:source:japan-mod` | `EMPTY` |
| `seed-meta:…:complete` | completion marker | never written |

`chinaCoverage` reports `military.cross-strait-activity` → `degraded` for the same reason.

Because the bootstrap key **is** written before the throw, the panel still renders — the failure is invisible in the UI and only shows up in `/api/health` and the crash channel.

Secondary cost: `seed-bundle-derived-signals` exits 1 on every tick (`ran:1 skipped:2 deferred:0 failed:1`), firing a Railway "Deploy Crashed!" alert and burning the run's compute each time. It is 100% deterministic — not a transient blip, and it will never self-heal.

## Fix

Wrap the hook so runSeed's meta object can't land in the writer slot, matching the idiom used by every other seeder, and export the wired hook so it is testable:

```js
export const crossStraitActivityAfterPublish = (snapshot) => writePublicationCompletion(snapshot);
// …
afterPublish: crossStraitActivityAfterPublish,
```

## Why the tests missed it

`tests/cross-strait-activity-shipping.test.mts:181,196` only ever calls `writePublicationCompletion(snapshot, writer, …)` with an **injected** writer, so the production call shape (arg 2 = meta object) is never exercised. The DI seam hid the wiring bug.

## Acceptance criteria

- [ ] Regression test calls the exported `afterPublish` hook with runSeed's exact shape — `hook(snapshot, { canonicalKey, ttlSeconds, recordCount, runId })` — and asserts the source-health + completion writes land. Test goes red against current `main` before the fix.
- [ ] `seed-bundle-derived-signals` completes with `failed:0` and exits 0.
- [ ] `/api/health` shows `crossStraitActivity` non-stale with a real `seedAgeMin`, and `crossStraitActivityTaiwanMnd` / `crossStraitActivityJapanMod` no longer `EMPTY`.

Found by `/diagnose-railway-seeders` on 2026-07-25 (service `seed-bundle-derived-signals`, class UNKNOWN/high).
